/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as QuizHistoryRouteImport } from './routes/quiz-history'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as MyPicksRouteImport } from './routes/my-picks'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as BetRouteImport } from './routes/bet'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeamsTeamCodeRouteImport } from './routes/teams.$teamCode'
import { Route as PlayersPlayerIdRouteImport } from './routes/players.$playerId'
import { Route as MatchesMatchIdRouteImport } from './routes/matches.$matchId'
import { Route as ApiPublicSyncMatchesRouteImport } from './routes/api/public/sync-matches'
import { Route as ApiPublicSyncEspnRouteImport } from './routes/api/public/sync-espn'
import { Route as ApiPublicSendPushRouteImport } from './routes/api/public/send-push'
import { Route as ApiPublicQuizTodayRouteImport } from './routes/api/public/quiz-today'
import { Route as ApiPublicQuizHistoryRouteImport } from './routes/api/public/quiz-history'
import { Route as ApiPublicQuizAnswerRouteImport } from './routes/api/public/quiz-answer'
import { Route as ApiPublicPlaceBetRouteImport } from './routes/api/public/place-bet'
import { Route as ApiPublicKarimRoastRouteImport } from './routes/api/public/karim-roast'
import { Route as ApiPublicKarimDailyRouteImport } from './routes/api/public/karim-daily'
import { Route as ApiPublicGrantStipendRouteImport } from './routes/api/public/grant-stipend'
import { Route as ApiPublicHooksEmitPendingPredictionsRouteImport } from './routes/api/public/hooks/emit-pending-predictions'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizHistoryRoute = QuizHistoryRouteImport.update({
  id: '/quiz-history',
  path: '/quiz-history',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const MyPicksRoute = MyPicksRouteImport.update({
  id: '/my-picks',
  path: '/my-picks',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const BetRoute = BetRouteImport.update({
  id: '/bet',
  path: '/bet',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsTeamCodeRoute = TeamsTeamCodeRouteImport.update({
  id: '/teams/$teamCode',
  path: '/teams/$teamCode',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersPlayerIdRoute = PlayersPlayerIdRouteImport.update({
  id: '/players/$playerId',
  path: '/players/$playerId',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesMatchIdRoute = MatchesMatchIdRouteImport.update({
  id: '/matches/$matchId',
  path: '/matches/$matchId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSyncMatchesRoute = ApiPublicSyncMatchesRouteImport.update({
  id: '/api/public/sync-matches',
  path: '/api/public/sync-matches',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSyncEspnRoute = ApiPublicSyncEspnRouteImport.update({
  id: '/api/public/sync-espn',
  path: '/api/public/sync-espn',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSendPushRoute = ApiPublicSendPushRouteImport.update({
  id: '/api/public/send-push',
  path: '/api/public/send-push',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicQuizTodayRoute = ApiPublicQuizTodayRouteImport.update({
  id: '/api/public/quiz-today',
  path: '/api/public/quiz-today',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicQuizHistoryRoute = ApiPublicQuizHistoryRouteImport.update({
  id: '/api/public/quiz-history',
  path: '/api/public/quiz-history',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicQuizAnswerRoute = ApiPublicQuizAnswerRouteImport.update({
  id: '/api/public/quiz-answer',
  path: '/api/public/quiz-answer',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPlaceBetRoute = ApiPublicPlaceBetRouteImport.update({
  id: '/api/public/place-bet',
  path: '/api/public/place-bet',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicKarimRoastRoute = ApiPublicKarimRoastRouteImport.update({
  id: '/api/public/karim-roast',
  path: '/api/public/karim-roast',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicKarimDailyRoute = ApiPublicKarimDailyRouteImport.update({
  id: '/api/public/karim-daily',
  path: '/api/public/karim-daily',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGrantStipendRoute = ApiPublicGrantStipendRouteImport.update({
  id: '/api/public/grant-stipend',
  path: '/api/public/grant-stipend',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksEmitPendingPredictionsRoute =
  ApiPublicHooksEmitPendingPredictionsRouteImport.update({
    id: '/api/public/hooks/emit-pending-predictions',
    path: '/api/public/hooks/emit-pending-predictions',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/bet': typeof BetRoute
  '/feed': typeof FeedRoute
  '/leaderboard': typeof LeaderboardRoute
  '/my-picks': typeof MyPicksRoute
  '/quiz': typeof QuizRoute
  '/quiz-history': typeof QuizHistoryRoute
  '/results': typeof ResultsRoute
  '/settings': typeof SettingsRoute
  '/matches/$matchId': typeof MatchesMatchIdRoute
  '/players/$playerId': typeof PlayersPlayerIdRoute
  '/teams/$teamCode': typeof TeamsTeamCodeRoute
  '/api/public/grant-stipend': typeof ApiPublicGrantStipendRoute
  '/api/public/karim-daily': typeof ApiPublicKarimDailyRoute
  '/api/public/karim-roast': typeof ApiPublicKarimRoastRoute
  '/api/public/place-bet': typeof ApiPublicPlaceBetRoute
  '/api/public/quiz-answer': typeof ApiPublicQuizAnswerRoute
  '/api/public/quiz-history': typeof ApiPublicQuizHistoryRoute
  '/api/public/quiz-today': typeof ApiPublicQuizTodayRoute
  '/api/public/send-push': typeof ApiPublicSendPushRoute
  '/api/public/sync-espn': typeof ApiPublicSyncEspnRoute
  '/api/public/sync-matches': typeof ApiPublicSyncMatchesRoute
  '/api/public/hooks/emit-pending-predictions': typeof ApiPublicHooksEmitPendingPredictionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/bet': typeof BetRoute
  '/feed': typeof FeedRoute
  '/leaderboard': typeof LeaderboardRoute
  '/my-picks': typeof MyPicksRoute
  '/quiz': typeof QuizRoute
  '/quiz-history': typeof QuizHistoryRoute
  '/results': typeof ResultsRoute
  '/settings': typeof SettingsRoute
  '/matches/$matchId': typeof MatchesMatchIdRoute
  '/players/$playerId': typeof PlayersPlayerIdRoute
  '/teams/$teamCode': typeof TeamsTeamCodeRoute
  '/api/public/grant-stipend': typeof ApiPublicGrantStipendRoute
  '/api/public/karim-daily': typeof ApiPublicKarimDailyRoute
  '/api/public/karim-roast': typeof ApiPublicKarimRoastRoute
  '/api/public/place-bet': typeof ApiPublicPlaceBetRoute
  '/api/public/quiz-answer': typeof ApiPublicQuizAnswerRoute
  '/api/public/quiz-history': typeof ApiPublicQuizHistoryRoute
  '/api/public/quiz-today': typeof ApiPublicQuizTodayRoute
  '/api/public/send-push': typeof ApiPublicSendPushRoute
  '/api/public/sync-espn': typeof ApiPublicSyncEspnRoute
  '/api/public/sync-matches': typeof ApiPublicSyncMatchesRoute
  '/api/public/hooks/emit-pending-predictions': typeof ApiPublicHooksEmitPendingPredictionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/bet': typeof BetRoute
  '/feed': typeof FeedRoute
  '/leaderboard': typeof LeaderboardRoute
  '/my-picks': typeof MyPicksRoute
  '/quiz': typeof QuizRoute
  '/quiz-history': typeof QuizHistoryRoute
  '/results': typeof ResultsRoute
  '/settings': typeof SettingsRoute
  '/matches/$matchId': typeof MatchesMatchIdRoute
  '/players/$playerId': typeof PlayersPlayerIdRoute
  '/teams/$teamCode': typeof TeamsTeamCodeRoute
  '/api/public/grant-stipend': typeof ApiPublicGrantStipendRoute
  '/api/public/karim-daily': typeof ApiPublicKarimDailyRoute
  '/api/public/karim-roast': typeof ApiPublicKarimRoastRoute
  '/api/public/place-bet': typeof ApiPublicPlaceBetRoute
  '/api/public/quiz-answer': typeof ApiPublicQuizAnswerRoute
  '/api/public/quiz-history': typeof ApiPublicQuizHistoryRoute
  '/api/public/quiz-today': typeof ApiPublicQuizTodayRoute
  '/api/public/send-push': typeof ApiPublicSendPushRoute
  '/api/public/sync-espn': typeof ApiPublicSyncEspnRoute
  '/api/public/sync-matches': typeof ApiPublicSyncMatchesRoute
  '/api/public/hooks/emit-pending-predictions': typeof ApiPublicHooksEmitPendingPredictionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/bet'
    | '/feed'
    | '/leaderboard'
    | '/my-picks'
    | '/quiz'
    | '/quiz-history'
    | '/results'
    | '/settings'
    | '/matches/$matchId'
    | '/players/$playerId'
    | '/teams/$teamCode'
    | '/api/public/grant-stipend'
    | '/api/public/karim-daily'
    | '/api/public/karim-roast'
    | '/api/public/place-bet'
    | '/api/public/quiz-answer'
    | '/api/public/quiz-history'
    | '/api/public/quiz-today'
    | '/api/public/send-push'
    | '/api/public/sync-espn'
    | '/api/public/sync-matches'
    | '/api/public/hooks/emit-pending-predictions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/bet'
    | '/feed'
    | '/leaderboard'
    | '/my-picks'
    | '/quiz'
    | '/quiz-history'
    | '/results'
    | '/settings'
    | '/matches/$matchId'
    | '/players/$playerId'
    | '/teams/$teamCode'
    | '/api/public/grant-stipend'
    | '/api/public/karim-daily'
    | '/api/public/karim-roast'
    | '/api/public/place-bet'
    | '/api/public/quiz-answer'
    | '/api/public/quiz-history'
    | '/api/public/quiz-today'
    | '/api/public/send-push'
    | '/api/public/sync-espn'
    | '/api/public/sync-matches'
    | '/api/public/hooks/emit-pending-predictions'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/bet'
    | '/feed'
    | '/leaderboard'
    | '/my-picks'
    | '/quiz'
    | '/quiz-history'
    | '/results'
    | '/settings'
    | '/matches/$matchId'
    | '/players/$playerId'
    | '/teams/$teamCode'
    | '/api/public/grant-stipend'
    | '/api/public/karim-daily'
    | '/api/public/karim-roast'
    | '/api/public/place-bet'
    | '/api/public/quiz-answer'
    | '/api/public/quiz-history'
    | '/api/public/quiz-today'
    | '/api/public/send-push'
    | '/api/public/sync-espn'
    | '/api/public/sync-matches'
    | '/api/public/hooks/emit-pending-predictions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  BetRoute: typeof BetRoute
  FeedRoute: typeof FeedRoute
  LeaderboardRoute: typeof LeaderboardRoute
  MyPicksRoute: typeof MyPicksRoute
  QuizRoute: typeof QuizRoute
  QuizHistoryRoute: typeof QuizHistoryRoute
  ResultsRoute: typeof ResultsRoute
  SettingsRoute: typeof SettingsRoute
  MatchesMatchIdRoute: typeof MatchesMatchIdRoute
  PlayersPlayerIdRoute: typeof PlayersPlayerIdRoute
  TeamsTeamCodeRoute: typeof TeamsTeamCodeRoute
  ApiPublicGrantStipendRoute: typeof ApiPublicGrantStipendRoute
  ApiPublicKarimDailyRoute: typeof ApiPublicKarimDailyRoute
  ApiPublicKarimRoastRoute: typeof ApiPublicKarimRoastRoute
  ApiPublicPlaceBetRoute: typeof ApiPublicPlaceBetRoute
  ApiPublicQuizAnswerRoute: typeof ApiPublicQuizAnswerRoute
  ApiPublicQuizHistoryRoute: typeof ApiPublicQuizHistoryRoute
  ApiPublicQuizTodayRoute: typeof ApiPublicQuizTodayRoute
  ApiPublicSendPushRoute: typeof ApiPublicSendPushRoute
  ApiPublicSyncEspnRoute: typeof ApiPublicSyncEspnRoute
  ApiPublicSyncMatchesRoute: typeof ApiPublicSyncMatchesRoute
  ApiPublicHooksEmitPendingPredictionsRoute: typeof ApiPublicHooksEmitPendingPredictionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz-history': {
      id: '/quiz-history'
      path: '/quiz-history'
      fullPath: '/quiz-history'
      preLoaderRoute: typeof QuizHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-picks': {
      id: '/my-picks'
      path: '/my-picks'
      fullPath: '/my-picks'
      preLoaderRoute: typeof MyPicksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bet': {
      id: '/bet'
      path: '/bet'
      fullPath: '/bet'
      preLoaderRoute: typeof BetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/$teamCode': {
      id: '/teams/$teamCode'
      path: '/teams/$teamCode'
      fullPath: '/teams/$teamCode'
      preLoaderRoute: typeof TeamsTeamCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players/$playerId': {
      id: '/players/$playerId'
      path: '/players/$playerId'
      fullPath: '/players/$playerId'
      preLoaderRoute: typeof PlayersPlayerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches/$matchId': {
      id: '/matches/$matchId'
      path: '/matches/$matchId'
      fullPath: '/matches/$matchId'
      preLoaderRoute: typeof MatchesMatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sync-matches': {
      id: '/api/public/sync-matches'
      path: '/api/public/sync-matches'
      fullPath: '/api/public/sync-matches'
      preLoaderRoute: typeof ApiPublicSyncMatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sync-espn': {
      id: '/api/public/sync-espn'
      path: '/api/public/sync-espn'
      fullPath: '/api/public/sync-espn'
      preLoaderRoute: typeof ApiPublicSyncEspnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/send-push': {
      id: '/api/public/send-push'
      path: '/api/public/send-push'
      fullPath: '/api/public/send-push'
      preLoaderRoute: typeof ApiPublicSendPushRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/quiz-today': {
      id: '/api/public/quiz-today'
      path: '/api/public/quiz-today'
      fullPath: '/api/public/quiz-today'
      preLoaderRoute: typeof ApiPublicQuizTodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/quiz-history': {
      id: '/api/public/quiz-history'
      path: '/api/public/quiz-history'
      fullPath: '/api/public/quiz-history'
      preLoaderRoute: typeof ApiPublicQuizHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/quiz-answer': {
      id: '/api/public/quiz-answer'
      path: '/api/public/quiz-answer'
      fullPath: '/api/public/quiz-answer'
      preLoaderRoute: typeof ApiPublicQuizAnswerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/place-bet': {
      id: '/api/public/place-bet'
      path: '/api/public/place-bet'
      fullPath: '/api/public/place-bet'
      preLoaderRoute: typeof ApiPublicPlaceBetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/karim-roast': {
      id: '/api/public/karim-roast'
      path: '/api/public/karim-roast'
      fullPath: '/api/public/karim-roast'
      preLoaderRoute: typeof ApiPublicKarimRoastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/karim-daily': {
      id: '/api/public/karim-daily'
      path: '/api/public/karim-daily'
      fullPath: '/api/public/karim-daily'
      preLoaderRoute: typeof ApiPublicKarimDailyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/grant-stipend': {
      id: '/api/public/grant-stipend'
      path: '/api/public/grant-stipend'
      fullPath: '/api/public/grant-stipend'
      preLoaderRoute: typeof ApiPublicGrantStipendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/emit-pending-predictions': {
      id: '/api/public/hooks/emit-pending-predictions'
      path: '/api/public/hooks/emit-pending-predictions'
      fullPath: '/api/public/hooks/emit-pending-predictions'
      preLoaderRoute: typeof ApiPublicHooksEmitPendingPredictionsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  BetRoute: BetRoute,
  FeedRoute: FeedRoute,
  LeaderboardRoute: LeaderboardRoute,
  MyPicksRoute: MyPicksRoute,
  QuizRoute: QuizRoute,
  QuizHistoryRoute: QuizHistoryRoute,
  ResultsRoute: ResultsRoute,
  SettingsRoute: SettingsRoute,
  MatchesMatchIdRoute: MatchesMatchIdRoute,
  PlayersPlayerIdRoute: PlayersPlayerIdRoute,
  TeamsTeamCodeRoute: TeamsTeamCodeRoute,
  ApiPublicGrantStipendRoute: ApiPublicGrantStipendRoute,
  ApiPublicKarimDailyRoute: ApiPublicKarimDailyRoute,
  ApiPublicKarimRoastRoute: ApiPublicKarimRoastRoute,
  ApiPublicPlaceBetRoute: ApiPublicPlaceBetRoute,
  ApiPublicQuizAnswerRoute: ApiPublicQuizAnswerRoute,
  ApiPublicQuizHistoryRoute: ApiPublicQuizHistoryRoute,
  ApiPublicQuizTodayRoute: ApiPublicQuizTodayRoute,
  ApiPublicSendPushRoute: ApiPublicSendPushRoute,
  ApiPublicSyncEspnRoute: ApiPublicSyncEspnRoute,
  ApiPublicSyncMatchesRoute: ApiPublicSyncMatchesRoute,
  ApiPublicHooksEmitPendingPredictionsRoute:
    ApiPublicHooksEmitPendingPredictionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
