/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as MyPicksRouteImport } from './routes/my-picks'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlayersPlayerIdRouteImport } from './routes/players.$playerId'
import { Route as MatchesMatchIdRouteImport } from './routes/matches.$matchId'
import { Route as ApiPublicSyncMatchesRouteImport } from './routes/api/public/sync-matches'
import { Route as ApiPublicSendPushRouteImport } from './routes/api/public/send-push'
import { Route as ApiPublicKarimRoastRouteImport } from './routes/api/public/karim-roast'
import { Route as ApiPublicKarimDailyRouteImport } from './routes/api/public/karim-daily'
import { Route as ApiPublicHooksEmitPendingPredictionsRouteImport } from './routes/api/public/hooks/emit-pending-predictions'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const MyPicksRoute = MyPicksRouteImport.update({
  id: '/my-picks',
  path: '/my-picks',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersPlayerIdRoute = PlayersPlayerIdRouteImport.update({
  id: '/players/$playerId',
  path: '/players/$playerId',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesMatchIdRoute = MatchesMatchIdRouteImport.update({
  id: '/matches/$matchId',
  path: '/matches/$matchId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSyncMatchesRoute = ApiPublicSyncMatchesRouteImport.update({
  id: '/api/public/sync-matches',
  path: '/api/public/sync-matches',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSendPushRoute = ApiPublicSendPushRouteImport.update({
  id: '/api/public/send-push',
  path: '/api/public/send-push',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicKarimRoastRoute = ApiPublicKarimRoastRouteImport.update({
  id: '/api/public/karim-roast',
  path: '/api/public/karim-roast',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicKarimDailyRoute = ApiPublicKarimDailyRouteImport.update({
  id: '/api/public/karim-daily',
  path: '/api/public/karim-daily',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksEmitPendingPredictionsRoute =
  ApiPublicHooksEmitPendingPredictionsRouteImport.update({
    id: '/api/public/hooks/emit-pending-predictions',
    path: '/api/public/hooks/emit-pending-predictions',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/feed': typeof FeedRoute
  '/leaderboard': typeof LeaderboardRoute
  '/my-picks': typeof MyPicksRoute
  '/settings': typeof SettingsRoute
  '/matches/$matchId': typeof MatchesMatchIdRoute
  '/players/$playerId': typeof PlayersPlayerIdRoute
  '/api/public/karim-daily': typeof ApiPublicKarimDailyRoute
  '/api/public/karim-roast': typeof ApiPublicKarimRoastRoute
  '/api/public/send-push': typeof ApiPublicSendPushRoute
  '/api/public/sync-matches': typeof ApiPublicSyncMatchesRoute
  '/api/public/hooks/emit-pending-predictions': typeof ApiPublicHooksEmitPendingPredictionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/feed': typeof FeedRoute
  '/leaderboard': typeof LeaderboardRoute
  '/my-picks': typeof MyPicksRoute
  '/settings': typeof SettingsRoute
  '/matches/$matchId': typeof MatchesMatchIdRoute
  '/players/$playerId': typeof PlayersPlayerIdRoute
  '/api/public/karim-daily': typeof ApiPublicKarimDailyRoute
  '/api/public/karim-roast': typeof ApiPublicKarimRoastRoute
  '/api/public/send-push': typeof ApiPublicSendPushRoute
  '/api/public/sync-matches': typeof ApiPublicSyncMatchesRoute
  '/api/public/hooks/emit-pending-predictions': typeof ApiPublicHooksEmitPendingPredictionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/feed': typeof FeedRoute
  '/leaderboard': typeof LeaderboardRoute
  '/my-picks': typeof MyPicksRoute
  '/settings': typeof SettingsRoute
  '/matches/$matchId': typeof MatchesMatchIdRoute
  '/players/$playerId': typeof PlayersPlayerIdRoute
  '/api/public/karim-daily': typeof ApiPublicKarimDailyRoute
  '/api/public/karim-roast': typeof ApiPublicKarimRoastRoute
  '/api/public/send-push': typeof ApiPublicSendPushRoute
  '/api/public/sync-matches': typeof ApiPublicSyncMatchesRoute
  '/api/public/hooks/emit-pending-predictions': typeof ApiPublicHooksEmitPendingPredictionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/feed'
    | '/leaderboard'
    | '/my-picks'
    | '/settings'
    | '/matches/$matchId'
    | '/players/$playerId'
    | '/api/public/karim-daily'
    | '/api/public/karim-roast'
    | '/api/public/send-push'
    | '/api/public/sync-matches'
    | '/api/public/hooks/emit-pending-predictions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/feed'
    | '/leaderboard'
    | '/my-picks'
    | '/settings'
    | '/matches/$matchId'
    | '/players/$playerId'
    | '/api/public/karim-daily'
    | '/api/public/karim-roast'
    | '/api/public/send-push'
    | '/api/public/sync-matches'
    | '/api/public/hooks/emit-pending-predictions'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/feed'
    | '/leaderboard'
    | '/my-picks'
    | '/settings'
    | '/matches/$matchId'
    | '/players/$playerId'
    | '/api/public/karim-daily'
    | '/api/public/karim-roast'
    | '/api/public/send-push'
    | '/api/public/sync-matches'
    | '/api/public/hooks/emit-pending-predictions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  FeedRoute: typeof FeedRoute
  LeaderboardRoute: typeof LeaderboardRoute
  MyPicksRoute: typeof MyPicksRoute
  SettingsRoute: typeof SettingsRoute
  MatchesMatchIdRoute: typeof MatchesMatchIdRoute
  PlayersPlayerIdRoute: typeof PlayersPlayerIdRoute
  ApiPublicKarimDailyRoute: typeof ApiPublicKarimDailyRoute
  ApiPublicKarimRoastRoute: typeof ApiPublicKarimRoastRoute
  ApiPublicSendPushRoute: typeof ApiPublicSendPushRoute
  ApiPublicSyncMatchesRoute: typeof ApiPublicSyncMatchesRoute
  ApiPublicHooksEmitPendingPredictionsRoute: typeof ApiPublicHooksEmitPendingPredictionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-picks': {
      id: '/my-picks'
      path: '/my-picks'
      fullPath: '/my-picks'
      preLoaderRoute: typeof MyPicksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players/$playerId': {
      id: '/players/$playerId'
      path: '/players/$playerId'
      fullPath: '/players/$playerId'
      preLoaderRoute: typeof PlayersPlayerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches/$matchId': {
      id: '/matches/$matchId'
      path: '/matches/$matchId'
      fullPath: '/matches/$matchId'
      preLoaderRoute: typeof MatchesMatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sync-matches': {
      id: '/api/public/sync-matches'
      path: '/api/public/sync-matches'
      fullPath: '/api/public/sync-matches'
      preLoaderRoute: typeof ApiPublicSyncMatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/send-push': {
      id: '/api/public/send-push'
      path: '/api/public/send-push'
      fullPath: '/api/public/send-push'
      preLoaderRoute: typeof ApiPublicSendPushRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/karim-roast': {
      id: '/api/public/karim-roast'
      path: '/api/public/karim-roast'
      fullPath: '/api/public/karim-roast'
      preLoaderRoute: typeof ApiPublicKarimRoastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/karim-daily': {
      id: '/api/public/karim-daily'
      path: '/api/public/karim-daily'
      fullPath: '/api/public/karim-daily'
      preLoaderRoute: typeof ApiPublicKarimDailyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/emit-pending-predictions': {
      id: '/api/public/hooks/emit-pending-predictions'
      path: '/api/public/hooks/emit-pending-predictions'
      fullPath: '/api/public/hooks/emit-pending-predictions'
      preLoaderRoute: typeof ApiPublicHooksEmitPendingPredictionsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  FeedRoute: FeedRoute,
  LeaderboardRoute: LeaderboardRoute,
  MyPicksRoute: MyPicksRoute,
  SettingsRoute: SettingsRoute,
  MatchesMatchIdRoute: MatchesMatchIdRoute,
  PlayersPlayerIdRoute: PlayersPlayerIdRoute,
  ApiPublicKarimDailyRoute: ApiPublicKarimDailyRoute,
  ApiPublicKarimRoastRoute: ApiPublicKarimRoastRoute,
  ApiPublicSendPushRoute: ApiPublicSendPushRoute,
  ApiPublicSyncMatchesRoute: ApiPublicSyncMatchesRoute,
  ApiPublicHooksEmitPendingPredictionsRoute:
    ApiPublicHooksEmitPendingPredictionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
